config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only:[] do
    collection do
      get 'search', to: 'pages#search'
      get 'match', to: 'pages#match'
    end
    member do
      get 'show', to: 'pages#show'
    end
  end


  resources :interactions, only: :create

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"

  after_save :check_match

  def check_match
    i = Interaction.where(user_one: self.user_two, user_two:self.user_one)
    unless i.empty?
      Match.create(user_one_id: self.user_one.id, user_two_id: self.user_two.id)
    end 
  end
end

app/models/match.rb
class Match < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :interactions_one, class_name: "Interaction", foreign_key: :user_one_id, dependent: :destroy
  has_many :interactions_two, class_name: "Interaction", foreign_key: :user_two_id, dependent: :destroy

  has_many :matches_one, class_name: "Match", foreign_key: :user_one_id, dependent: :destroy
  has_many :matches_two, class_name: "Match", foreign_key: :user_two_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:age, :gender, :name, :bio, :photo])
  end

end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  
  def create
    Interaction.create(user_one_id: current_user.id, user_two_id: params[:id_user], like: params[:me_gusta])
    redirect_to search_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def match
    @matches = Match.all
    @users = User.all
  end

  def search
    if user_signed_in?
      @user = User.where.not(id: current_user.id).sample
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinderlike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <% if user_signed_in? %>
      <br>
      <br>
      <%= link_to 'search', search_pages_path %>
      <%= link_to 'home', root_path %>
      <%= link_to 'Matchs', match_pages_path %>
    <% end %>

  </body>
</html>

app/views/pages/home.html.erb
<h4>Home</h4>

app/views/pages/match.html.erb
<h3>Your Matches</h3>

<% @matches.each do |match| %>
  <% if match.user_two_id == current_user.id %>
    <%= "Tienes un match con #{@users.find(match.user_one_id).name}"  %>
    <%= link_to 'Ver perfil', page_path(match.user_one_id) %>
  <% elsif match.user_one_id == current_user.id %>
    <%= "Tienes un match con #{@users.find(match.user_two_id).name}"  %>
    <%= link_to 'Ver perfil', page_path(match.user_two_id) %>
  <% else %>
    <%= "Aún no tienes nigún match!" %>
  <% end %>
  <br>
<% end %>

app/views/pages/search.html.erb
<h4>Search</h4>
<h2>
  <%= @user.email %><br>
  <%= @user.gender %>
  <%= @user.age %><br>
</h2>
<%= link_to 'Like', interactions_path(me_gusta: true, id_user: @user.id), method: 'post' %>
<%= link_to 'Unlike', interactions_path(me_gusta: false, id_user: @user.id), method: 'post' %>

app/views/pages/show.html.erb
<h3>Este es el Show</h3>
<%= @user.name %><br>
<%= @user.age %><br>
<%= @user.gender %><br>
<%= @user.bio %><br>
<%= @user.photo %>